filebeat_create_config: true
filebeat_rpm: /home/ansible/filebeat-7.17.10-x86_64.rpm
filebeat_src: /usr/src/filebeat-7.17.10-x86_64.rpm
cert_dir: /usr/src/certs/
filebeat_ssl_dir: /etc/filebeat/certs/
log_dir: /var/log/ansible/ansible.log*
module_template: "ansible_log.j2 "
filebeat_template: "filebeat_config.j2"

filebeat_inputs:
  - type: log
    paths:
      - "/var/log/*.log"

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "192.168.11.6:9200"

filebeat_output_elasticsearch_auth: {}

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "192.168.11.6:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log
